FROM airdock/oracle-jdk:latest
MAINTAINER Ciubara Ion <builtofire@gmail.com>

ENV CATALINA_HOME /opt/tomcat
ENV PATH $CATALINA_HOME/bin:$PATH
RUN mkdir -p "$CATALINA_HOME"
WORKDIR $CATALINA_HOME

RUN gpg --keyserver pool.sks-keyservers.net --recv-keys \
	05AB33110949707C93A279E3D3EFE6B686867BA6 \
	07E48665A34DCAFAE522E5E6266191C37C037D42 \
	47309207D818FFD8DCD3F83F1931D684307A10A5 \
	541FBE7D8F78B25E055DDEE13C370389288584E7 \
	61B832AC2F1C5A90F0F9B00A1C506407564C17A3 \
	713DA88BE50911535FE716F5208B0AB1D63011C7 \
	79F7026C690BAA50B92CD8B66A3AD3F4F22C4FED \
	9BA44C2621385CB966EBA586F72C284D731FABEE \
	A27677289986DB50844682F8ACB77FC2E86E29AC \
	A9C5DF4D22E99998D9875A5110C01C5A2F6059E7 \
	DCFD35E0BF8CA7344752DE8B6FB21E8933C60243 \
	F3A04C595DB5B6A5F1ECA43E3B7BBB100D811BBE \
	F7DA48BB64BCB84ECBA7EE6935CD23C10D498E23

ENV TOMCAT_MAJOR 8
ENV TOMCAT_VERSION 8.0.35
ENV TOMCAT_TGZ_URL https://www.apache.org/dist/tomcat/tomcat-$TOMCAT_MAJOR/v$TOMCAT_VERSION/bin/apache-tomcat-$TOMCAT_VERSION.tar.gz

RUN set -x \
	&& curl -fSL "$TOMCAT_TGZ_URL" -o tomcat.tar.gz \
	&& curl -fSL "$TOMCAT_TGZ_URL.asc" -o tomcat.tar.gz.asc \
	&& gpg --verify tomcat.tar.gz.asc \
	&& tar -xvf tomcat.tar.gz --strip-components=1 \
	&& rm bin/*.bat \
	&& rm tomcat.tar.gz*


# install maven
ENV MAVEN_VERSION 3.3.9

RUN curl -fsSL https://archive.apache.org/dist/maven/maven-3/$MAVEN_VERSION/binaries/apache-maven-$MAVEN_VERSION-bin.tar.gz | tar xzf - -C /usr/share \
  && mv /usr/share/apache-maven-$MAVEN_VERSION /usr/share/maven \
  && ln -s /usr/share/maven/bin/mvn /usr/bin/mvn

ENV MAVEN_HOME /usr/share/maven

# build all
#RUN cd /root/entityman
#RUN mvn clean install -Dmaven.test.skip=true

# deploy
COPY ./target/emres.war $CATALINA_HOME/webapps/
ENV JAVA_OPTS "$JAVA_OPTS -Xmx4G -XX:MaxPermSize=1G -Djava.security.egd=file:/dev/./urandom"

EXPOSE 8080

#VOLUME /etc/entityman
#VOLUME /root/.m2
#VOLUME /opt

RUN mkdir /opt/entityman
RUN mkdir /opt/entityman/data

#RUNNING
WORKDIR $CATALINA_HOME/bin

CMD ["catalina.sh", "run"]
#CMD ["/bin/bash"]

################################################3
#FROM jetty:latest
#MAINTAINER Smári McCarthy <smari@occrp.org>
#
#RUN apt-get update
#RUN apt-get install -y maven mongodb
#
#RUN mkdir -p /srv/projects/entityman
#COPY . /srv/projects/entityman
#
#WORKDIR /srv/projects/entityman
#RUN mvn clean install
#
#CMD ["mvn", "jetty:run"]
